/**
 * githubClient.ts
 *
 * Thin adapter for creating documentation PRs via the GitHub REST API.
 * Uses Node.js built-in `https` module — no extra dependency required.
 *
 * This is the ONLY module in the codebase that makes network requests,
 * gated by the G1.5 exemption (ALLOW_NETWORK_TOOLS=true).
 */

import * as https from 'https';
import { CreatePRParams, DeletePRParams, GitHubPRResult } from './types';

export { CreatePRParams, DeletePRParams, GitHubPRResult } from './types';

export class GitHubClient {
  private baseUrl = 'api.github.com';

  /**
   * Create a documentation PR: branch → commit file → open PR.
   * Makes exactly 4 API calls (or 5 if updating an existing file).
   */
  async createDocsPR(params: CreatePRParams): Promise<GitHubPRResult> {
    try {
      // 1. Get main branch SHA
      const mainRef = await this.apiRequest<{ object: { sha: string } }>(
        'GET',
        params.token,
        `/repos/${params.owner}/${params.repo}/git/ref/heads/main`
      );
      const baseSha = mainRef.object.sha;

      // 2. Create branch
      const branchName = this.generateBranchName(params.title);
      await this.apiRequest(
        'POST',
        params.token,
        `/repos/${params.owner}/${params.repo}/git/refs`,
        {
          ref: `refs/heads/${branchName}`,
          sha: baseSha,
        }
      );

      // 3. Create/update file on the new branch
      const contentBase64 = Buffer.from(params.content, 'utf-8').toString('base64');
      const putBody: Record<string, unknown> = {
        message: `docs: ${params.title}`,
        content: contentBase64,
        branch: branchName,
      };

      // If updating an existing file, we need the current file SHA
      if (params.isUpdate) {
        try {
          const existing = await this.apiRequest<{ sha: string }>(
            'GET',
            params.token,
            `/repos/${params.owner}/${params.repo}/contents/${params.filePath}?ref=main`
          );
          putBody.sha = existing.sha;
        } catch {
          // File doesn't exist on main — treat as new file
        }
      }

      await this.apiRequest(
        'PUT',
        params.token,
        `/repos/${params.owner}/${params.repo}/contents/${params.filePath}`,
        putBody
      );

      // 4. Open PR
      const prBody = this.buildPRBody(params);
      const pr = await this.apiRequest<{ number: number; html_url: string }>(
        'POST',
        params.token,
        `/repos/${params.owner}/${params.repo}/pulls`,
        {
          title: `[Community Docs] ${params.title}`,
          head: branchName,
          base: 'main',
          body: prBody,
        }
      );

      return {
        success: true,
        prUrl: pr.html_url,
        prNumber: pr.number,
        branch: branchName,
      };
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      // Never leak auth tokens in error responses
      return {
        success: false,
        error: `Failed to create PR: ${message.replace(/token\s+\S+/gi, 'token [REDACTED]')}`,
      };
    }
  }

  /**
   * Generate a unique, sanitized branch name from the PR title.
   */
  generateBranchName(title: string): string {
    const timestamp = new Date()
      .toISOString()
      .replace(/[-:]/g, '')
      .replace(/\.\d+Z$/, 'Z');
    const slug = title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 40);
    return `docs/contrib/${timestamp}-${slug}`;
  }

  /**
   * Build the PR body with metadata and validation results.
   */
  private buildPRBody(params: CreatePRParams): string {
    const contributor = params.contributorName || 'Anonymous';
    const type = params.isUpdate ? 'Update to existing doc' : 'New documentation';
    const dupeLine = params.duplicateWarning
      ? `- ⚠️ ${params.duplicateWarning}`
      : '- ✅ No near-duplicates detected';
    const description = params.description || 'No description provided.';

    return [
      '## Community Documentation Contribution',
      '',
      `**Submitted via:** FeathersJS MCP Server (\`submit_documentation\` tool)`,
      `**Contributor:** ${contributor}`,
      `**Target version:** ${params.version}`,
      `**Category:** ${params.category || 'auto-detect'}`,
      `**File:** \`${params.filePath}\``,
      `**Type:** ${type}`,
      '',
      '### Validation Results',
      '- ✅ Schema validation passed',
      '- ✅ Path restrictions passed',
      '- ✅ Content sanitization passed',
      '- ✅ Markdown lint passed',
      dupeLine,
      '',
      '### Description',
      description,
      '',
      '---',
      '*This PR was automatically generated by the FeathersJS MCP Server contributor pipeline.',
      'Please review the content carefully before merging.*',
    ].join('\n');
  }

  /**
   * Create a PR that deletes a documentation file: branch → delete file → open PR.
   * Makes exactly 4 API calls.
   */
  async createRemovalPR(params: DeletePRParams): Promise<GitHubPRResult> {
    try {
      // 1. Get main branch SHA
      const mainRef = await this.apiRequest<{ object: { sha: string } }>(
        'GET',
        params.token,
        `/repos/${params.owner}/${params.repo}/git/ref/heads/main`
      );
      const baseSha = mainRef.object.sha;

      // 2. Create branch
      const branchName = this.generateBranchName(`remove-${params.filePath.split('/').pop()}`);
      await this.apiRequest(
        'POST',
        params.token,
        `/repos/${params.owner}/${params.repo}/git/refs`,
        {
          ref: `refs/heads/${branchName}`,
          sha: baseSha,
        }
      );

      // 3. Get file SHA on the new branch, then delete it
      const existing = await this.apiRequest<{ sha: string }>(
        'GET',
        params.token,
        `/repos/${params.owner}/${params.repo}/contents/${params.filePath}?ref=${branchName}`
      );

      await this.apiRequest(
        'DELETE',
        params.token,
        `/repos/${params.owner}/${params.repo}/contents/${params.filePath}`,
        {
          message: `docs: remove ${params.filePath}`,
          sha: existing.sha,
          branch: branchName,
        }
      );

      // 4. Open PR
      const prBody = this.buildRemovalPRBody(params);
      const pr = await this.apiRequest<{ number: number; html_url: string }>(
        'POST',
        params.token,
        `/repos/${params.owner}/${params.repo}/pulls`,
        {
          title: `[Community Docs] Remove ${params.filePath.split('/').pop()}`,
          head: branchName,
          base: 'main',
          body: prBody,
        }
      );

      return {
        success: true,
        prUrl: pr.html_url,
        prNumber: pr.number,
        branch: branchName,
      };
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      return {
        success: false,
        error: `Failed to create removal PR: ${message.replace(/token\s+\S+/gi, 'token [REDACTED]')}`,
      };
    }
  }

  /**
   * Build the PR body for a documentation removal.
   */
  private buildRemovalPRBody(params: DeletePRParams): string {
    const contributor = params.contributorName || 'Anonymous';
    return [
      '## Community Documentation Removal Request',
      '',
      `**Submitted via:** FeathersJS MCP Server (\`remove_documentation\` tool)`,
      `**Contributor:** ${contributor}`,
      `**Target version:** ${params.version}`,
      `**File:** \`${params.filePath}\``,
      '',
      '### Reason for Removal',
      params.reason,
      '',
      '### Validation Results',
      '- ✅ Path restrictions passed',
      '- ✅ Document existence verified',
      '',
      '---',
      '*This PR was automatically generated by the FeathersJS MCP Server contributor pipeline.',
      'Please review the removal request carefully before merging.*',
    ].join('\n');
  }

  /**
   * Generic GitHub API request using Node.js built-in https.
   */
  private apiRequest<T>(method: string, token: string, path: string, body?: unknown): Promise<T> {
    return new Promise<T>((resolve, reject) => {
      const options: https.RequestOptions = {
        hostname: this.baseUrl,
        path,
        method,
        headers: {
          Authorization: `Bearer ${token}`,
          Accept: 'application/vnd.github+json',
          'User-Agent': 'feathers-mcp-server/1.0.0',
          'X-GitHub-Api-Version': '2022-11-28',
        },
      };

      if (body) {
        (options.headers as Record<string, string>)['Content-Type'] = 'application/json';
      }

      const req = https.request(options, (res) => {
        let data = '';
        res.on('data', (chunk: Buffer) => {
          data += chunk.toString();
        });
        res.on('end', () => {
          const statusCode = res.statusCode ?? 0;
          if (statusCode >= 200 && statusCode < 300) {
            try {
              resolve(JSON.parse(data) as T);
            } catch {
              resolve(data as unknown as T);
            }
          } else if (statusCode === 401) {
            reject(new Error('Authentication failed. Check GITHUB_TOKEN.'));
          } else if (statusCode === 403) {
            reject(
              new Error(
                'Insufficient permissions. Token needs contents:write and pull_requests:write.'
              )
            );
          } else if (statusCode === 404) {
            reject(new Error('Repository not found. Check GITHUB_OWNER and GITHUB_REPO.'));
          } else if (statusCode === 422) {
            reject(new Error(`Validation failed (422): ${data}`));
          } else if (statusCode === 429) {
            reject(new Error('GitHub API rate limit exceeded. Try again later.'));
          } else {
            reject(new Error(`GitHub API error (${statusCode}): ${data.slice(0, 200)}`));
          }
        });
      });

      req.on('error', (err) => {
        reject(new Error(`Network error: ${err.message}`));
      });

      // 30-second timeout for the HTTP request
      req.setTimeout(30000, () => {
        req.destroy();
        reject(new Error('GitHub API request timed out after 30 seconds.'));
      });

      if (body) {
        req.write(JSON.stringify(body));
      }
      req.end();
    });
  }
}

export default GitHubClient;
